// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Context;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240613133805_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Category1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Category2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Category3"
                        });
                });

            modelBuilder.Entity("WebApplication1.Entity.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Email = "e1@e.e",
                            FirstName = "name1",
                            LastName = "last1",
                            Mobile = "11"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Email = "e2@e.e",
                            FirstName = "name2",
                            LastName = "last2",
                            Mobile = "22"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Email = "e3@e.e",
                            FirstName = "name3",
                            LastName = "last3",
                            Mobile = "33"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Email = "e4@e.e",
                            FirstName = "name4",
                            LastName = "last4",
                            Mobile = "4444"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Email = "e5@e.e",
                            FirstName = "name5",
                            LastName = "last5",
                            Mobile = "55"
                        });
                });

            modelBuilder.Entity("WebApplication1.Entity.Contact", b =>
                {
                    b.HasOne("WebApplication1.Entity.Category", "Category")
                        .WithMany("Contacts")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApplication1.Entity.Category", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
