// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Context;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240622041240_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Category1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Category2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Category3"
                        });
                });

            modelBuilder.Entity("WebApplication1.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriorityType")
                        .HasColumnType("int");

                    b.Property<bool>("UnDeleteAble")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2011, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = 1,
                            Email = "e1@e.e",
                            FirstName = "name1",
                            LastName = "last1",
                            Mobile = "11",
                            PhotoPath = "/img/01.jpg",
                            PriorityType = 0,
                            UnDeleteAble = false
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2010, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = 1,
                            Email = "e2@e.e",
                            FirstName = "name2",
                            LastName = "last2",
                            Mobile = "22",
                            PhotoPath = "/img/02.jpg",
                            PriorityType = 1,
                            UnDeleteAble = true
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2012, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = 2,
                            Email = "e3@e.e",
                            FirstName = "name3",
                            LastName = "last3",
                            Mobile = "33",
                            PhotoPath = "/img/03.jpg",
                            PriorityType = 2,
                            UnDeleteAble = false
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2013, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = 2,
                            Email = "e4@e.e",
                            FirstName = "name4",
                            LastName = "last4",
                            Mobile = "4444",
                            PhotoPath = "/img/04.jpg",
                            PriorityType = 3,
                            UnDeleteAble = false
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Email = "e5@e.e",
                            FirstName = "name5",
                            LastName = "last5",
                            Mobile = "55",
                            PhotoPath = "/img/05.jpg",
                            PriorityType = 3,
                            UnDeleteAble = false
                        });
                });

            modelBuilder.Entity("WebApplication1.Entities.Contact", b =>
                {
                    b.HasOne("WebApplication1.Entities.Category", "Category")
                        .WithMany("Contacts")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApplication1.Entities.Category", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
